### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/nutshell-moose#2]
# User Stories
- [ ] As a user, when I am unauthenticated I should be able to see the dashboard (Read-only).
- [ ] As a user, when I am authenticated I should be able to perform all actions on the dashboard (full CRUD).
- [ ] As a user, I should be able to login via google.
- [ ] As a user, I should be able to logout.

# AC
**WHEN** a user is unauthenticated
**THEN** they can see the dashboard, but not edit it
**AND** when the user is authenticated
**THEN** they can sign in via google
**AND** they can perform all actions on the dashboard
**AND** they can successfully logout

# Dev Notes
### TODO:

- Login/Logout buttons are within the same `div` but display and hide depending on the User's login status
- Create a `checkLoginStatus()` function that checks Firebase for their login
- When logged out, print the dashboard as read-only

**Comment by petestewart** [comment]
**Authorization procedures:**
- Whenever printing a new dashboard to the DOM, you can call `authData.secureButtons()` and all items with a class of `.auth-only` will be hidden or unhidden depending on user's authorization.

- To check if a user is logged in (before running CRUD operations, etc.), call `authData.checkAuth()`. It will return `true` if the user is logged in and false they aren't.


**Login and Logout procedures:**
- Call `auth.signMeIn()` to sign in the current user.

- Login/logout buttons are referred to in `authData.js` with the id's of `#login-button` and `#logout-button`.
