### ISSUE TITLE
Staff Collection

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/nutshell-moose#7]
## User Stories
- [x] As a user, I should be able to add new staff members #21 
- [x] As a user, I should be able to delete staff members #24 
- [x] As a user, I should be able to edit the staff members #22 
- [x] As a user, I should be able to view all the staff members #19 
- [x] As a user, I should be able to filter the staff member list my staff member type (ie show only waiters or busboys) #25
